### ISSUE TITLE
[Style Guide] Add more on architecture

### ISSUE THREAD

**Issue by mishraanmol** [runthroughmedia/css#1]
[ ] 1. - OOCSS
[ ] 2. - DRY
[ ] 3. - Settings - Variables/Maps
[ ] 4. - Tools - Functions/Mixins

Provide example of how Toolkit is structured following closely to ITCSS
@runthroughmedia Any help with this??

**Comment by runthroughmedia** [comment]
TOP LEVEL: OOP and OOCSS

My background is both back and front end so I am going to give you a 50ft view so you can go fishing. I first started working with CSS before there were precompiler's. I had to create a hierarchy and work with the inheritance chain to build out custom style guides for my teams I built out.

Object Oriented CSS is no more than working with a sudo inheritance chain and custom objects/classes, helpers, mixins, etc. and then compile it into a minified file. The minified file and compiling process are beneficial for several reasons. Back in the wild wild west days of CSS, several years ago, you had to maintain a lot of code. That meant lots of objects and stacking lots of classes to get the desired look. When I brought on a new employee it was a huge pain to try and get everyone on the same page, even with a style guides and the ever changing face of standards. Also the browser only accepts so many requests. By compiling and building it to a minified file you make sure you have the best performance possible and no one can jack your code, at least not easily. Not so much the case now given the parsers that read and put the proper indents on the fly. Companies wanted this feature because they always want ownership over the code and it's hard to explain to them that front end code is open to the world.

So keep in mind an object oriented approach and apply the sexiness of the cascade while utilizing the precompilers logic and that really is all there is to it. Remember OOP when working with OOCSS. People make it much harder than it has to be. Job security will always be there if you master you craft.
